### PR TITLE
Checkpoint-Restart using HDF5

### PR DESCRIPTION
**Pull request by okulkarni**
Updates to the code to perform checkpoint-restarts using HDF5.

### CODE REVIEW

**Comment by brobey** [comment]
Omkar,
    I merged the changes in. It was a little messy for the merge, but I think I got your changes in. Yours have priority since I'd prefer the HDF5 and am still working out issues with the MPI I/O code.

Please check carefully that I did not break anything in the HDF5.

**Comment by brobey** [comment]
It looks like H5Pset_fapl_mpio has been removed from HDF5? Do I need to use an older version to compile the code?

**Comment by okulkarni** [comment]
Hi Bob, I was building it against @brtnfld's fast forward version, which I suppose has the old API:

https://git.hdfgroup.org/projects/HDFFV/repos/hdf5/browse

**Comment by brobey** [comment]
The merge did not go as well as I was hoping. I may even regress to your version if necessary. I’ll try backing up my HDF version on my laptop. The big computers probably have older versions and it won’t be a problem. I’m on travel right now so time and computer access are limited.

Bob

**Comment by brtnfld** [comment]
I don’t think you will be able to resolve the current hdf5 implementation with Omkar’s version, so I would just accept Omkar’s code base when doing the merge.

Scot


On Jan 26, 2017, at 2:18 PM, Bob Robey <notifications@github.com<mailto:notifications@github.com>> wrote:

The merge did not go as well as I was hoping. I may even regress to your version if necessary. I’ll try backing up my HDF version on my laptop. The big computers probably have older versions and it won’t be a problem. I’m on travel right now so time and computer access are limited.

Bob

**Comment by brobey** [comment]
I just reverted to your original pull request until I have time to sort things out with the mpi io

**Pull request merged**
